### ISSUE TITLE
destructor TgxSceneViewport.Destroy;  problem at compilation time.

### ISSUE THREAD

**Issue by juanccilleruelo** [GLScene/GLXcene#3]
FreeAndNil(TObject(FMultisample)); line

Says: [dcc32 Error] GXS.ViewerOpenGL.pas(119): E2197 Constant object cannot be passed as var parameter

**Comment by juanccilleruelo** [comment]
Compiling with Delphi 10.3 Update 2.

**Comment by GLScene** [comment]
Use GLX.ViewerOpenGL.pas unit, try it.
